site_name: Fiori Tracker
site_url: https://fioritracker.org
site_description: 'Fiori Tracker simplifies SAP Fiori app management. Centralized platform for collaborating on requirements.'
nav:
  - User manual: user-manual.md
  - Learn more: learn-more.md
  - Installation: inst.md
  - Support: support.md  
  - Philosophy: philosophy.md   
  - Impressum: impressum.md

# Explicitly confirm there is awareness of files not in nav
not_in_nav: |
  /index.md
  /*/
  /as-is.md
  /bugs-ideas.md
  /com.md
  /comp-main.md
  /contact-success.md
  /faq.md
  /info-records.md
  /info.md
  /premier.md
  /satisfied-intrests-and-roles.md
  /to-be.md
  /tracked.md
  /ui5lib-options.md
  /usecases.md

# Together with --strict flag it allows to crash CI if an error occurs and prevent shipping broken sites
validation:
  nav:
    omitted_files: warn
    not_found: warn
    absolute_links: warn  # If needed change to 'relative_to_docs'
  links:
    not_found: warn
    anchors: warn
    absolute_links: warn  # If needed change to 'relative_to_docs'
    unrecognized_links: warn
theme: 
  name: 'material'
  favicon: 'assets/images/favicon.ico'
  logo: 'assets/images/logo.png'
  custom_dir: overrides
extra_css:
  - stylesheets/extra.css
extra_javascript:
  - assets/javascripts/extra.js
markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
hooks:
  - overrides/hooks/change_logo_for_social_cards.py
  - overrides/hooks/adjust_redirects_html.py
plugins:
  - search
  - macros
  - blog:
      blog_dir: usecases
      post_url_format: "{slug}"
      post_readtime: false
  - social:
      enabled: !ENV [CI, false]
      cards_layout_options:
        background_color: "#0d0d72"  # same color as the corner in the social_logo.png
  - redirects:
      # file redirects return a status 200 code, but redirect the page via <head> tags
      # keep it for a few weeks to see if the online search results will change or if we 
      # have to only use the 404.html page + JavaScript approach, even though robots don't run JS
      redirect_maps:
        '1909FPS03.md': 'index.md'
        '1909SPS06.md': 'index.md'
        '1909SPS08.md': 'index.md'
        '2020.md': 'index.md'
        '2020FPS01.md': 'index.md'
        'installation.md': 'index.md'
        'V2020.md': 'index.md'
        'V2020/ac/FPS01/inst-opt.md': 'ac/FPS01/inst-opt.md'
        'V2020/ac/FPS01/inst.md': 'ac/FPS01/inst.md'
        'V2020/ac/FPS01/main.md': 'ac/FPS01/main.md'
        'V2020/ai/FPS01/main.md': 'ai/FPS01/main.md'
        'V2020/apps-rel-appsusage/FPS01/main.md': 'apps-rel-appsusage/FPS01/main.md'
        'V2020/apps-rel-catalogs-asis/FPS01/main.md': 'apps-rel-catalogs-asis/FPS01/main.md'
        'V2020/as-is.md': 'as-is.md'
        'V2020/asis/FPS01/inst-cen.md': 'asis/FPS01/inst-cen.md'
        'V2020/asis/FPS01/inst-man.md': 'asis/FPS01/inst-man.md'
        'V2020/asis/FPS01/sys.md': 'asis/FPS01/sys.md'
        'V2020/asis/SPS02/dependents.md': 'asis/SPS02/dependents.md'
        'V2020/asis/SPS02/inst-cen.md': 'asis/SPS02/inst-cen.md'
        'V2020/asis/SPS02/inst.md': 'asis/SPS02/inst.md'
        'V2020/asis/SPS02/sync.md': 'asis/SPS02/sync.md'
        'V2020/asis/SPS02/sys.md': 'asis/SPS02/sys.md'
        'V2020/bugs-ideas.md': 'bugs-ideas.md'
        'V2020/ca/FPS01/det.md': 'ca/FPS01/det.md'
        'V2020/ca/FPS01/inst-opt.md': 'ca/FPS01/inst-opt.md'
        'V2020/ca/FPS01/main.md': 'ca/FPS01/main.md'
        'V2020/cat-app/SPS02/main.md': 'cat-app/SPS02/main.md'
        'V2020/cats-rel-apps-asis/FPS01/main.md': 'cats-rel-apps-asis/FPS01/main.md'
        'V2020/ch/FPS01/eval-dep.md': 'ch/FPS01/eval-dep.md'
        'V2020/ch/FPS01/inst-opt.md': 'ch/FPS01/inst-opt.md'
        'V2020/ch/FPS01/inst.md': 'ch/FPS01/inst.md'
        'V2020/ch/FPS01/main.md': 'ch/FPS01/main.md'
        'V2020/ci/SPS02/main.md': 'ci/SPS02/main.md'
        'V2020/co/FPS01/conf.md': 'co/FPS01/conf.md'
        'V2020/co/FPS01/main.md': 'co/FPS01/main.md'
        'V2020/com.md': 'com.md'
        'V2020/comp-main.md': 'comp-main.md'
        'V2020/core/SPS02/main.md': 'core/SPS02/main.md'
        'V2020/core/SPS02/tech.md': 'core/SPS02/tech.md'
        'V2020/core/SPS03/apps-rel-tobe-cats.md': 'core/SPS03/apps-rel-tobe-cats.md'
        'V2020/core/SPS03/cats-rel-tobe-apps.md': 'core/SPS03/cats-rel-tobe-apps.md'
        'V2020/core/SPS03/cats.md': 'core/SPS03/cats.md'
        'V2020/core/SPS03/conf.md': 'core/SPS03/conf.md'
        'V2020/core/SPS03/core-apps.md': 'core/SPS03/core-apps.md'
        'V2020/core/SPS03/eval-dep.md': 'core/SPS03/eval-dep.md'
        'V2020/core/SPS03/inst.md': 'core/SPS03/inst.md'
        'V2020/core/SPS03/main.md': 'core/SPS03/main.md'
        'V2020/core/SPS03/rel.md': 'core/SPS03/rel.md'
        'V2020/cr/FPS01/eval-dep.md': 'cr/FPS01/eval-dep.md'
        'V2020/cr/FPS01/inst.md': 'cr/FPS01/inst.md'
        'V2020/cr/FPS01/main.md': 'cr/FPS01/main.md'
        'V2020/cr/SPS02/inst.md': 'cr/SPS02/inst.md'
        'V2020/cr/SPS02/main.md': 'cr/SPS02/main.md'
        'V2020/cr/SPS02/tech.md': 'cr/SPS02/tech.md'
        'V2020/fa/FPS01/main.md': 'fa/FPS01/main.md'
        'V2020/faq.md': 'faq.md'
        'V2020/gv/FPS01/main.md': 'gv/FPS01/main.md'
        'V2020/hi/FPS01/conf.md': 'hi/FPS01/conf.md'
        'V2020/hi/FPS01/main.md': 'hi/FPS01/main.md'
        'V2020/impressum.md': 'impressum.md'
        'V2020/info-records.md': 'info-records.md'
        'V2020/inst.md': 'inst.md'
        'V2020/inst/comp.md': 'inst/comp.md'
        'V2020/inst/dep.md': 'inst/dep.md'
        'V2020/inst/flpcache.md': 'inst/flpcache.md'
        'V2020/inst/min.md': 'inst/min.md'
        'V2020/inst/rfc.md': 'inst/rfc.md'
        'V2020/inst/step-1.md': 'inst/step-1.md'
        'V2020/inst/step-2.md': 'inst/step-2.md'
        'V2020/inst/step-3.md': 'inst/step-3.md'
        'V2020/inst/step-4.md': 'inst/step-4.md'
        'V2020/learn-more.md': 'learn-more.md'
        'V2020/philosophy.md': 'philosophy.md'
        'V2020/premier.md': 'premier.md'
        'V2020/rel-ch/FPS01/main.md': 'rel-ch/FPS01/main.md'
        'V2020/rel-so/FPS01/main.md': 'rel-so/FPS01/main.md'
        'V2020/ro/FPS01/inst-opt.md': 'ro/FPS01/inst-opt.md'
        'V2020/ro/FPS01/inst.md': 'ro/FPS01/inst.md'
        'V2020/ro/FPS01/main.md': 'ro/FPS01/main.md'
        'V2020/ro/FPS01/roles.md': 'ro/FPS01/roles.md'
        'V2020/satisfied-intrests-and-roles.md': 'satisfied-intrests-and-roles.md'
        'V2020/so/FPS01/conf.md': 'so/FPS01/conf.md'
        'V2020/so/FPS01/inst-opt.md': 'so/FPS01/inst-opt.md'
        'V2020/suite/SPS03/main.md': 'suite/SPS03/main.md'
        'V2020/support.md': 'support.md'
        'V2020/tracked.md': 'tracked.md'
        'V2020/tracked/SPS03/app-cats-asis.md': 'tracked/SPS03/app-cats-asis.md'
        'V2020/tracked/SPS03/app-cats-tobe.md': 'tracked/SPS03/app-cats-tobe.md'
        'V2020/tracked/SPS03/app-hist.md': 'tracked/SPS03/app-hist.md'
        'V2020/tracked/SPS03/app-roles.md': 'tracked/SPS03/app-roles.md'
        'V2020/tracked/SPS03/app-usage.md': 'tracked/SPS03/app-usage.md'
        'V2020/tracked/SPS03/apps.md': 'tracked/SPS03/apps.md'
        'V2020/tracked/SPS03/appsusage.md': 'tracked/SPS03/appsusage.md'
        'V2020/tracked/SPS03/cat-apps-asis.md': 'tracked/SPS03/cat-apps-asis.md'
        'V2020/tracked/SPS03/cat-apps-tobe.md': 'tracked/SPS03/cat-apps-tobe.md'
        'V2020/tracked/SPS03/cat-change-req.md': 'tracked/SPS03/cat-change-req.md'
        'V2020/tracked/SPS03/cat-hist.md': 'tracked/SPS03/cat-hist.md'
        'V2020/tracked/SPS03/cat-sign-offs.md': 'tracked/SPS03/cat-sign-offs.md'
        'V2020/tracked/SPS03/cats.md': 'tracked/SPS03/cats.md'
        'V2020/tracked/SPS03/changereq.md': 'tracked/SPS03/changereq.md'
        'V2020/tracked/SPS03/history.md': 'tracked/SPS03/history.md'
        'V2020/tracked/SPS03/role-cats.md': 'tracked/SPS03/role-cats.md'
        'V2020/tracked/SPS03/role-change-req.md': 'tracked/SPS03/role-change-req.md'
        'V2020/tracked/SPS03/role-comments.md': 'tracked/SPS03/role-comments.md'
        'V2020/tracked/SPS03/role-hist.md': 'tracked/SPS03/role-hist.md'
        'V2020/tracked/SPS03/role-sign-offs.md': 'tracked/SPS03/role-sign-offs.md'
        'V2020/tracked/SPS03/role-test-users.md': 'tracked/SPS03/role-test-users.md'
        'V2020/tracked/SPS03/roles.md': 'tracked/SPS03/roles.md'
        'V2020/tracked/SPS03/signoff.md': 'tracked/SPS03/signoff.md'
        'V2020/tracked/SPS03/testusers.md': 'tracked/SPS03/testusers.md'
        'V2020/tu/FPS01/conf.md': 'tu/FPS01/conf.md'
        'V2020/tu/FPS01/inst-opt.md': 'tu/FPS01/inst-opt.md'
        'V2020/tu/FPS01/inst.md': 'tu/FPS01/inst.md'
        'V2020/tu/FPS01/main.md': 'tu/FPS01/main.md'
        'V2020/ui5lib-options.md': 'ui5lib-options.md'
        'V2020/usecases.md': 'usecases/index.md'
        'V2020/usecases/SPS03/adding-app.md': 'usecases/posts/adding-app.md'
        'V2020/usecases/SPS03/auto-prov.md': 'usecases/posts/auto-prov.md'
        'V2020/usecases/SPS03/changes-history.md': 'usecases/posts/changes-history.md'
        'V2020/usecases/SPS03/clarity-of-resp.md': 'usecases/posts/clarity-of-resp.md'
        'V2020/usecases/SPS03/eval-impact.md': 'usecases/posts/eval-impact.md'
        'V2020/usecases/SPS03/naming-apps.md': 'usecases/posts/naming-apps.md'
        'V2020/usecases/SPS03/naming.md': 'usecases/posts/naming.md'
        'V2020/usecases/SPS03/recording-test-results.md': 'usecases/posts/recording-test-results.md'
        'V2020/usecases/SPS03/requirements-gathering.md': 'usecases/posts/requirements-gathering.md'
        'V2020/usecases/SPS03/scope-control.md': 'usecases/posts/scope-control.md'
        'V2020/usecases/SPS03/spreadsheet-challenges.md': 'usecases/posts/spreadsheet-challenges.md'
        'V2020/usecases/SPS03/tech-category.md': 'usecases/posts/tech-category.md'
        'V2020/usecases/SPS03/test-users.md': 'usecases/posts/test-users.md'
        'V2020/usecases/SPS03/transparency.md': 'usecases/posts/transparency.md'
copyright: Copyright &copy; 2016 - 2024 Nype
extra:
  analytics:
    provider: google
    property: G-3SXC9PW73K 
  social:
    - icon: fontawesome/solid/building
      link: https://npe.cm/?ref=fioritracker
    - icon: fontawesome/brands/github
      link: https://github.com/fioritracker/
    - icon: fontawesome/brands/linkedin-in
      link: https://linkedin.com/company/fiori-tracker/
    - icon: fontawesome/brands/x-twitter
      link: https://twitter.com/fioritracker
    - icon: fontawesome/brands/facebook-f
      link: https://facebook.com/fioritracker/
    - icon: fontawesome/brands/youtube
      link: https://youtube.com/channel/UC6bx5QiaM3KRE8qgshBrurg
    - icon: fontawesome/brands/discord
      link: https://discord.gg/xGNzmej4KE
  prod:  
    core:
      name: 'Fiori Tracker Core'
      desc: 'Applications and Catalogs "To-be" records and their association'
      nameshort: 'Core'
      main: '2020'
      latestrel: 'SPS03'
      cen: 'X'
      man: ' '
      rep: 'installation'
      pay: 'free'
    asisCen:
      name: 'As-is main: API'
      desc: 'Enables Managed systems data synchronization'
      nameshort: 'As-is API'
      main: '2020'
      latestrel: 'SPS02'
      cen: 'X'
      man: ' '
      rep: 'asis-cen'
      pay: 'free'
    asisMan:
      name: 'As-is Connector'
      main: '2020'
      latestrel: 'SPS02'
      cen: 'X'
      man: 'X'
      rep: 'asis-man'
      pay: 'free'
    catAppRep:
      name: 'Catalog and App reports'
      desc: 'Catalog and Apps "As-is" records and their association'
      main: '2020'
      latestrel: 'SPS02'
      cen: 'X'
      man: ' '
      rep: 'catapprep'
      pay: 'free'  
    cr:
      name: 'Catalog Report'
      main: '2020'
      latestrel: 'SPS02'
      cen: 'X'
      man: ' '
      rep: 'cat-rep'
      pay: 'free'
    ac:
      name: 'App Catalogs Report'
      main: '2020'
      latestrel: 'FPS01'
      cen: 'X'
      man: ' '
      rep: 'ac'
      pay: 'free'
    ca:
      name: 'Catalog Apps Report'
      main: '2020'
      latestrel: 'FPS01'
      cen: 'X'
      man: ' '
      rep: 'ca'
      pay: 'free'
    fa:
      name: 'Fiori Apps Usage Report'
      desc: 'Fiori Apps Usage Report is a component that enables collecting usage records.'
      main: '2020'
      latestrel: 'FPS01'
      cen: 'X'
      man: ' '
      rep: 'fa'
      pay: 'paid'
    fap:
      name: 'Fiori Apps Usage Plugin'
      main: '2020'
      latestrel: 'FPS01'
      cen: 'X'
      man: 'X'
      rep: 'fap'
      pay: 'paid'
    ftCatsRelAppsAsis:
      name: 'FT Catalogs Relation: Apps As-is'
      main: '2020'
      latestrel: 'FPS01'
      cen: 'X'
      man: ' '
      rep: 'asis-cen'
      pay: 'free'
    ftAppsRelCatsAsis:
      name: 'FT Apps Relation: Catalogs, As-is'
      main: '2020'
      latestrel: 'FPS01'
      cen: 'X'
      man: ' '
      rep: 'asis-cen'
      pay: 'free'
    ftAppsRelAppsUsage:
      name: 'FT Apps Relation: Apps` Usage'
      main: '2020'
      latestrel: 'FPS01'
      cen: 'X'
      man: ' '
      rep: 'fa'
      pay: 'paid'
    ch:
      name: 'Change Requests'
      desc: 'Change request records linked to catalogs and apps'
      main: '2020'
      latestrel: 'FPS01'
      cen: 'X'
      man: ' '
      rep: 'ch'
      pay: 'free'
    RelCh:
      name: 'FT Apps and Catalogs Relation: Change Requests'
      desc: 'The Change Request relation shows a list of change requests linked to an application or catalog.'
      main: '2020'
      latestrel: 'FPS01'
      cen: 'X'
      man: ' '
      rep: 'ch'
      pay: 'free'  
    so:
      name: 'Sign-offs'
      desc: 'The Sign-offs app lets you create, change and list sign-offs records linked to all content types (apps, catalogs and roles)'
      main: '2020'
      latestrel: 'FPS01'
      cen: 'X'
      man: ' '
      rep: 'so'
      pay: 'free'
    tu:
      name: 'Test users'
      nameshort: 'Test users'
      desc: 'The Test users app lets you create, change, and list test user records.'
      main: '2020'
      latestrel: 'FPS01'
      cen: 'X'
      man: ' '
      rep: 'tu'
      pay: 'free'
    RelTu:
      name: 'FT Apps Relation: Test users'
      desc: 'The Test users relation shows a list of test users linked to all apps'
      main: '2020'
      latestrel: 'FPS01'
      cen: 'X'
      man: ' '
      rep: 'tu'
      pay: 'free'      
    hi:
      name: 'History'
      nameshort: 'History'
      desc: 'The History component keeps the history records for SAP Fiori launchpad key deliverables: apps, catalogs, and roles.'
      main: '2020'
      latestrel: 'FPS01'
      cen: 'X'
      man: ' '
      rep: 'hi'
      pay: 'free'
    co:
      name: 'Comments'
      nameshort: 'Comments'
      desc: 'The Comments component keeps the free text notes records for SAP Fiori launchpad key deliverables: apps, catalogs, and roles.'
      main: '2020'
      latestrel: 'FPS01'
      cen: 'X'
      man: ' '
      rep: 'co'
      pay: 'free'
    RelSo:
      name: 'FT Apps and Catalogs Relation: Sign-offs'
      desc: 'The Sign-offs relation shows a list of sign-offs linked to all content types (apps, catalogs and roles)'
      main: '2020'
      latestrel: 'FPS01'
      cen: 'X'
      man: ' '
      rep: 'so'
      pay: 'free'
    ro:
      name: 'Fiori Tracker Roles'
      nameshort: 'Roles'
      desc: 'Roles "To-be" records and their association to apps through catalogs'
      main: '2020'
      latestrel: 'FPS01'
      cen: 'X'
      man: ' '
      rep: 'ro'
      pay: 'free'
    ci:
      name: 'Catalog Import'
      nameshort: 'Catalog Import'
      desc: 'Lets you import catalogs from your system into the "To-be" catalogs list'
      main: '2020'
      latestrel: 'SPS02'
      cen: 'X'
      man: ' '
      rep: 'ci'
      pay: 'paid'
    ai:
      name: 'Application Import'
      nameshort: 'Apps Import'
      desc: 'Lets you import applications from your system into the "To-be" application list'
      main: '2020'
      latestrel: 'FPS01'
      cen: 'X'
      man: ' '
      rep: 'ai'
      pay: 'paid'
    mi:
      name: 'Mapping Import'
      nameshort: 'Mapping Import'
      desc: 'Lets you import mappings of the applications to catalogs'
      main: '2020'
      latestrel: 'FPS01'
      cen: 'X'
      man: ' '
      rep: 'mi'
      pay: 'paid'
    RelRo:
      name: 'FT Apps and Catalogs Relation: Roles'
      desc: 'The Roles relation shows a list of sign-offs linked to all content types (apps, catalogs and roles)'
      main: '2020'
      latestrel: 'FPS01'
      cen: 'X'
      man: ' '
      rep: 'ro'
      pay: 'free'
    gv:
      name: 'Gover'
      nameshort: 'Gover'
      desc: 'Gover is a solution that enables security checks for your SAP system landscape.'
      main: '2020'
      latestrel: 'FPS01'
      cen: 'X'
      man: ' '
      rep: 'gv'
      pay: 'paid'
