name: Sitemap

#on: [ push, pull_request ]
on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}

      - name: Build Sitemap
        run: |
          git pull --rebase
          cd /2020SPS02
          ./sitemap.sh
      - name: Commit Updated
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Build sitemap.xml
